route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email-notifications'

receivers:
- name: 'email-notifications'         # Receiver name
  email_configs:
  - to: kimgh9407@gmail.com       # Email recipient
    from: ghkim.dev@gmail.com              # Email sender
    smarthost: smtp.gmail.com:587     # SMTP server
    auth_username: ghkim.dev@gmail.com  # SMTP auth username
    auth_identity: ghkim.dev@gmail.com  # SMTP auth identity
    auth_password: "hipl ewtm jqpp mtkz"  # SMTP auth password
    send_resolved: true               # Send notifications for resolved alerts

inhibit_rules:
  - source_match:
      severity: 'critical'            # Source alert severity
    target_match:
      severity: 'warning'             # Target alert severity
    equal: ['alertname', 'dev', 'instance']  # Fields to match
